const API_BASE_URL = "http://localhost:5008";

// Helper: Generate unique ID for users and audits
const generateId = (prefix) =>
  `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;

export const registerUser = async (data) => {
  // Transform frontend data to match backend expectations
  const payload = {
    id: generateId("user"),
    name: data.username,
    email: data.email,
    role: data.role,
    organization: data.organization || "",
    createdBy: "admin", // Backend requires this field
    // permissions are auto-generated by chaincode based on role
  };

  const response = await fetch(`${API_BASE_URL}/users/register`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  const res = await handle_response(response);

  if (res.success) {
    // Fetch the full user data to return to frontend
    const userResponse = await fetch(`${API_BASE_URL}/users/${res.userId}`);
    const userData = await handle_response(userResponse);
    return userData.data;
  }
  throw new Error(res.error || "Registration failed");
};

export const getUser = async (userId) => {
  const response = await fetch(`${API_BASE_URL}/users/${userId}`);
  const res = await handle_response(response);
  return res.data; // Backend returns {success, data: {...}}
};

export const updateUserRole = async (userId, data) => {
  const response = await fetch(`${API_BASE_URL}/users/${userId}/role`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data),
  });
  const res = await handle_response(response);

  // Backend returns {success, message, userId, newRole}
  // Fetch updated user data to return complete object
  const userResponse = await fetch(`${API_BASE_URL}/users/${userId}`);
  const userData = await handle_response(userResponse);
  return userData.data;
};

export const logAudit = async (data) => {
  // Add ID if not provided
  const payload = {
    id: data.id || generateId("audit"),
    ...data,
  };

  const response = await fetch(`${API_BASE_URL}/audit/log`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });
  const res = await handle_response(response);

  if (res.success) {
    // Fetch the audit entry to return full data
    const auditResponse = await fetch(`${API_BASE_URL}/audit/${res.auditId}`);
    const auditData = await handle_response(auditResponse);
    return auditData.data;
  }
  throw new Error(res.error || "Logging audit failed");
};

export const getAudit = async (auditId) => {
  const response = await fetch(`${API_BASE_URL}/audit/${auditId}`);
  const res = await handle_response(response);
  return res.data; // Backend returns {success, data: {...}}
};

export const getAllAudits = async () => {
  const response = await fetch(`${API_BASE_URL}/audit/all`);
  const res = await handle_response(response);
  return res.data; // Backend returns {success, count, data: [...]}
};

export const queryAuditsByUser = async (userId) => {
  const response = await fetch(`${API_BASE_URL}/audit/all`);
  const res = await handle_response(response);
  const allAudits = res.data;

  // Client-side filter by userId
  const filtered = allAudits.filter((audit) => audit.userId === userId);
  return filtered;
};

export const queryAuditsByAction = async (action) => {
  const response = await fetch(`${API_BASE_URL}/audit/all`);
  const res = await handle_response(response);
  const allAudits = res.data;

  // Client-sde filter by action
  const filtered = allAudits.filter((audit) => audit.action === action);
  return filtered;
};

export const queryAuditsByDateRange = async (startDate, endDate) => {
  const response = await fetch(`${API_BASE_URL}/audit/all`);
  const res = await handle_response(response);
  const allAudits = res.data;

  // Client-side filter by timestamp range
  const filtered = allAudits.filter(
    (audit) => audit.timestamp >= startDate && audit.timestamp <= endDate
  );
  return filtered;
};

export const generateComplianceReport = async (data) => {
  throw new Error(
    "Compliance reports are not yet implemented. This feature is coming in a future release."
  );
};

export const getComplianceReport = async (reportId) => {
  throw new Error(
    "Compliance reports are not yet implemented. This feature is coming in a future release."
  );
};

export const getAllReports = async () => {
  throw new Error(
    "Compliance reports are not yett implemented. This feature is coming in a future release."
  );
};

async function handle_response(response) {
  const data = await response.json();
  if (response.ok === false || data.success === false) {
    const messageFromServer = data.error || data.details;
    const defaultMessage = `Error: ${response.status}`;
    throw new Error(messageFromServer || defaultMessage);
  }
  return data;
}
